---
version: ">= 1.0.0"
os: linux
dist: xenial
language: shell


_rubocop__project_dir: &rubocop__project_dir
  language: ruby
  before_script:
    - 'gem install --conservative --minimal-deps rubocop'
  script:
    - 'rubocop --fail-level warning --display-only-fail-level-offenses set_travis_env_vars'

jobs:
  include:
###  Testing on Travis CI is indefinitely disabled
###
###  See:
###    * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
###    * https://simp-project.atlassian.net/browse/SIMP-8703
###  - stage:  validation
###    name:   'JSON syntax'
###    script:
###      - bash -c 'for json in $(find . -type f -name "*.json"); do echo "== $json" && jq . "$json"; done'
###
###  - stage:  validation
###    name:   Shellcheck
###    allow_failure: true
###    script:
###    - bash -c 'find . -type f -name "*.sh"  | xargs shellcheck'
###
###  - stage:  validation
###    name:   'YAML lint'
###    language: ruby
###    before_script:
###      - 'gem install --conservative --minimal-deps yaml-lint'
###    script:
###      - bash -c 'find . -type f -name "*.yaml" -o -name "*.yml" | xargs yaml-lint'
###
###  - stage:  validation
###    name:   'Rubocop: set_travis_env_vars'
###    env: PROJECT_DIR="set_travis_env_vars"
###    <<: *rubocop__project_dir
###
###  - stage:  validation
###    name:   'Rubocop: octokit-repo-puncher'
###    env: PROJECT_DIR="octokit-repo-puncher"
###    <<: *rubocop__project_dir
###
###  - stage:  validation
###    name:   'Rubocop: Boltdir'
###    env: PROJECT_DIR="Boltdir"
###    <<: *rubocop__project_dir
###
###  - stage:  validation
###    name:   'Bolt: Boltdir provides `releng::` tasks'
###    before_script:
###      - wget https://apt.puppet.com/puppet-tools-release-xenial.deb
###      - sudo dpkg -i puppet-tools-release-xenial.deb
###      - sudo apt-get update
###      - sudo apt-get install puppet-bolt
###    script:
###      - 'BOLT_DISABLE_ANALYTICS=yes bolt task show | grep releng::'
